header: '&6     Server Rules     '
rule1: '&a1.There are no rules'
rule2: '&a2.Yet chat is monitored for younger audiences'
rule3: '&a3.The owner has a right to anarchy such as removing lag machines'